// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// HASI geo index v0 DDL smoke tests (design doc HASI_POC.md §7 v0-②):
//  1. st_s2_cellid values are bit-identical to the C++ golden values (the same set the
//     FE-side S2CellKeyCompatibilityTest pins — three-way FE-Java/BE-C++/SQL agreement).
//  2. DUP table with the __s2 generated column as DUPLICATE KEY prefix works end to end.
//  3. UNIQUE MOW + CLUSTER BY containing a generated column: FE validation passes but
//     there is no repo precedent — this test turns the assumption into a tested fact.
suite("s2_generated_column") {
    sql "SET enable_nereids_planner=true;"
    sql "SET enable_fallback_to_original_planner=false;"

    // ---- 1. function golden values (generated by C++ s2geometry 0.10.0) ----
    def golden = [
            [116.397d, 39.909d, -5336674574189580231L],
            [-73.985d, 40.748d, 703223077213776591L],
            [151.215d, -33.857d, -1507951169714816409L],
            [0.0d, 0.0d, -8070450532247928831L],
            [-135.0d, 0.0d, 2113689425112552789L],   // raw id has the top bit set: sign-flip guard
            [180.0d, 0.0d, -1152921504606846977L],
            [-180.0d, 0.0d, -1152921504606846975L],
            [0.0d, 90.0d, -3458764513820540927L],
            [0.0d, -90.0d, 3458764513820540929L],
    ]
    golden.each { row ->
        def res = sql "select st_s2_cellid(${row[0]}, ${row[1]})"
        assertEquals(row[2], res[0][0])
    }
    // invalid coordinates / NULL propagation -> NULL
    def nullCases = sql """select st_s2_cellid(181.0, 0.0), st_s2_cellid(0.0, 91.0),
                                  st_s2_cellid(NULL, 0.0), st_s2_cellid(0.0, NULL)"""
    assertEquals(null, nullCases[0][0])
    assertEquals(null, nullCases[0][1])
    assertEquals(null, nullCases[0][2])
    assertEquals(null, nullCases[0][3])

    // ---- 2. DUP table: generated __s2 as DUPLICATE KEY prefix ----
    sql "drop table if exists geo_s2_gencol_dup"
    sql """
    create table geo_s2_gencol_dup (
        `__s2` bigint generated always as (st_s2_cellid(`lon`, `lat`)) null,
        `event_day` date not null,
        `id` bigint not null,
        `lon` double null,
        `lat` double null
    ) engine=olap
    duplicate key(`__s2`, `event_day`)
    distributed by hash(`id`) buckets 4
    properties("replication_num" = "1");
    """
    sql """insert into geo_s2_gencol_dup(event_day, id, lon, lat) values
        ('2026-07-14', 1, 116.397, 39.909),
        ('2026-07-14', 2, -73.985, 40.748),
        ('2026-07-14', 3, 151.215, -33.857),
        ('2026-07-14', 4, -135.0, 0.0),
        ('2026-07-14', 5, null, 40.0);"""
    sql "sync"

    // generated values match the scalar function bit-for-bit
    def mismatch = sql """select count(*) from geo_s2_gencol_dup
                          where lon is not null
                            and (__s2 is null or __s2 != st_s2_cellid(lon, lat))"""
    assertEquals(0L, mismatch[0][0])
    // NULL lon -> NULL __s2 (row must still load)
    def nullRow = sql "select __s2 from geo_s2_gencol_dup where id = 5"
    assertEquals(null, nullRow[0][0])
    // Hilbert order == BIGINT order on the sign-flipped key (face 4 city sorts after face-0/1/2 ones)
    qt_dup_order "select id, __s2 from geo_s2_gencol_dup order by __s2, id"
    // schema survives SHOW CREATE (generated column + key prefix rendered faithfully)
    def createStmt = sql "show create table geo_s2_gencol_dup"
    assertTrue(createStmt[0][1].contains("st_s2_cellid"))
    assertTrue(createStmt[0][1].contains("DUPLICATE KEY(`__s2`"))

    // ---- 3. UNIQUE MOW + CLUSTER BY with a generated column (no repo precedent) ----
    sql "drop table if exists geo_s2_gencol_mow"
    sql """
    create table geo_s2_gencol_mow (
        `id` bigint not null,
        `__s2` bigint generated always as (st_s2_cellid(`lon`, `lat`)) null,
        `event_day` date not null,
        `lon` double null,
        `lat` double null
    ) engine=olap
    unique key(`id`)
    cluster by(`__s2`, `event_day`)
    distributed by hash(`id`) buckets 4
    properties("replication_num" = "1", "enable_unique_key_merge_on_write" = "true");
    """
    sql """insert into geo_s2_gencol_mow(id, event_day, lon, lat) values
        (1, '2026-07-14', 116.397, 39.909),
        (2, '2026-07-14', -73.985, 40.748),
        (3, '2026-07-14', 151.215, -33.857);"""
    // MOW upsert: moving a point must update __s2 through the generated column
    sql "insert into geo_s2_gencol_mow(id, event_day, lon, lat) values (2, '2026-07-14', 2.294, 48.858);"
    sql "sync"

    def mowMismatch = sql """select count(*) from geo_s2_gencol_mow
                             where __s2 is null or __s2 != st_s2_cellid(lon, lat)"""
    assertEquals(0L, mowMismatch[0][0])
    def moved = sql "select __s2 from geo_s2_gencol_mow where id = 2"
    assertEquals(-4042420598571231353L, moved[0][0]) // paris golden value
    qt_mow_order "select id, __s2 from geo_s2_gencol_mow order by __s2, id"
}
