// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package org.apache.doris.geo;

import com.google.common.geometry.S2CellId;
import com.google.common.geometry.S2LatLng;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * Cross-language contract test for the HASI geo index (design doc §3.3-1 / v0-⑤):
 * the Java S2 port (com.google.geometry:s2-geometry, used by the FE to turn query
 * geometries into __s2 ranges) must produce bit-identical leaf cell ids to the C++
 * s2geometry the BE links (st_s2_cellid / GeoPoint::ComputeS2CellKey), and both sides
 * must agree on the order-preserving signed key transform __s2 = cellId ^ 2^63.
 *
 * <p>The golden values below were generated by C++ s2geometry 0.10.0 from
 * thirdparty/installed (cities, poles, antimeridian, face corners/edges, equator).
 * If this test fails after an S2 upgrade on either side, the FE-computed __s2 ranges
 * would silently drop rows — do NOT relax it; align the two library versions instead.
 */
public class S2CellKeyCompatibilityTest {

    /** rows: lng, lat, expected signed key (C++ raw cell id XOR 2^63, as int64). */
    private static final double[][] COORDS = {
            {116.397000, 39.909000}, {-73.985000, 40.748000}, {2.294000, 48.858000},
            {151.215000, -33.857000}, {0.000000, 0.000000}, {45.000000, 0.000000},
            {-45.000000, 0.000000}, {135.000000, 0.000000}, {-135.000000, 0.000000},
            {180.000000, 0.000000}, {-180.000000, 0.000000}, {180.000000, 45.000000},
            {0.000000, 90.000000}, {0.000000, -90.000000}, {12.000000, 89.999000},
            {30.000000, -89.999000}, {0.000000, 45.000000}, {90.000000, 45.000000},
            {179.999900, -0.000100}, {-179.999900, 0.000100}, {33.333300, 66.666600},
            {-122.419000, 37.775000},
    };

    private static final long[] EXPECTED_KEYS = {
            -5336674574189580231L, 703223077213776591L, -4042420598571231353L,
            -1507951169714816409L, -8070450532247928831L, -7493989779944505345L,
            -8646911284551352319L, -5572453938933093717L, 2113689425112552789L,
            -1152921504606846977L, -1152921504606846975L, -2113689425112552789L,
            -3458764513820540927L, 3458764513820540929L, -4227378850064129129L,
            3458764514063133675L, -7878296948146787669L, -5188146770730811393L,
            -1152921504611325253L, -384307168197804049L, -4309964325416661775L,
            37577590239227441L,
    };

    @Test
    public void testCellKeyMatchesCppGolden() {
        for (int i = 0; i < COORDS.length; i++) {
            double lng = COORDS[i][0];
            double lat = COORDS[i][1];
            long rawId = S2CellId.fromLatLng(S2LatLng.fromDegrees(lat, lng)).id();
            long key = rawId ^ Long.MIN_VALUE;
            Assertions.assertEquals(EXPECTED_KEYS[i], key,
                    String.format("cell key mismatch at lng=%f lat=%f (Java raw id=%d)",
                            lng, lat, rawId));
        }
    }

    @Test
    public void testKeyTransformPreservesHilbertOrder() {
        // Faces in Hilbert order: their range_min leaf keys must be strictly increasing
        // as signed longs. Raw ids would NOT be (faces 4/5 have the top bit set).
        long prevKey = Long.MIN_VALUE;
        boolean sawNegativeRawOrderBreak = false;
        long prevRaw = Long.MIN_VALUE;
        for (int face = 0; face < 6; face++) {
            long raw = S2CellId.fromFace(face).rangeMin().id();
            long key = raw ^ Long.MIN_VALUE;
            Assertions.assertTrue(key > prevKey, "face " + face + " key order");
            if (face > 0 && raw < prevRaw) {
                sawNegativeRawOrderBreak = true;
            }
            prevKey = key;
            prevRaw = raw;
        }
        // Sanity: the raw-id order really is broken for signed longs (face 4 goes
        // negative), i.e. the XOR transform is load-bearing, not decorative.
        Assertions.assertTrue(sawNegativeRawOrderBreak,
                "expected raw ids to break signed order at face 4 — did the encoding change?");
    }
}
